name: Build and GH-Page Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install deps
        run: yarn

      - name: Build package
        run: |
          yarn
          yarn build
      - name: Build project
        run: |
          cd examples/basic/
          yarn
          yarn build
      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: examples/dist
